# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: leagueclone
email: your-email@domain.com

# Build settings
markdown: kramdown
baseurl: /league-clone

prose: 
  ignore: ["_includes", "_layouts", "_site", "css", "js", "img"]
